# log.console = true
# log.console.level = debug

auth_backends.1 = rabbit_auth_backend_oauth2
auth_backends.2 = rabbit_auth_backend_internal # basic auth

management.oauth_enabled = true
management.oauth_client_id = <KEYCLOAK_CLIENT_ID> # rabbitmq
management.oauth_client_secret = <KEYCLOAK_CLIENT_SECRET>
management.oauth_provider_url = https://<KEYCLOAK_HOSTNAME>/realms/<KEYCLOAK_REALM>
management.oauth_scopes = openid profile
management.oauth_disable_basic_auth = false # enable basic auth form

auth_oauth2.resource_server_id = <KEYCLOAK_CLIENT_ID>  # rabbitmq
auth_oauth2.preferred_username_claims.1 = preferred_username
auth_oauth2.additional_scopes_key = roles
auth_oauth2.issuer = https://<KEYCLOAK_HOSTNAME>/realms/<KEYCLOAK_REALM>
# Allows connection to Keycloak with a wildcard certificate (*.example.com)
# RabbitMQ can download JWKS and OpenID-configuration without the TLS hostname_check_failed error.
# auth_oauth2.https.hostname_verification = wildcard
